// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sportsline.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sport         []string               `protobuf:"bytes,1,rep,name=sport,proto3" json:"sport,omitempty"`
	Interval      *durationpb.Duration   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_sportsline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sportsline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_sportsline_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSport() []string {
	if x != nil {
		return x.Sport
	}
	return nil
}

func (x *SubscribeRequest) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sports        map[string]float32     `protobuf:"bytes,1,rep,name=sports,proto3" json:"sports,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_sportsline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sportsline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_sportsline_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetSports() map[string]float32 {
	if x != nil {
		return x.Sports
	}
	return nil
}

var File_sportsline_proto protoreflect.FileDescriptor

const file_sportsline_proto_rawDesc = "" +
	"\n" +
	"\x10sportsline.proto\x12\x05proto\x1a\x1egoogle/protobuf/duration.proto\"_\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05sport\x18\x01 \x03(\tR\x05sport\x125\n" +
	"\binterval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\binterval\"\x8c\x01\n" +
	"\x11SubscribeResponse\x12<\n" +
	"\x06sports\x18\x01 \x03(\v2$.proto.SubscribeResponse.SportsEntryR\x06sports\x1a9\n" +
	"\vSportsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012e\n" +
	"\x12SportsLinesService\x12O\n" +
	"\x16SubscribeOnSportsLines\x12\x17.proto.SubscribeRequest\x1a\x18.proto.SubscribeResponse(\x010\x01B%Z#kiddy-line-processor/internal/protob\x06proto3"

var (
	file_sportsline_proto_rawDescOnce sync.Once
	file_sportsline_proto_rawDescData []byte
)

func file_sportsline_proto_rawDescGZIP() []byte {
	file_sportsline_proto_rawDescOnce.Do(func() {
		file_sportsline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sportsline_proto_rawDesc), len(file_sportsline_proto_rawDesc)))
	})
	return file_sportsline_proto_rawDescData
}

var file_sportsline_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sportsline_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: proto.SubscribeRequest
	(*SubscribeResponse)(nil),   // 1: proto.SubscribeResponse
	nil,                         // 2: proto.SubscribeResponse.SportsEntry
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_sportsline_proto_depIdxs = []int32{
	3, // 0: proto.SubscribeRequest.interval:type_name -> google.protobuf.Duration
	2, // 1: proto.SubscribeResponse.sports:type_name -> proto.SubscribeResponse.SportsEntry
	0, // 2: proto.SportsLinesService.SubscribeOnSportsLines:input_type -> proto.SubscribeRequest
	1, // 3: proto.SportsLinesService.SubscribeOnSportsLines:output_type -> proto.SubscribeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sportsline_proto_init() }
func file_sportsline_proto_init() {
	if File_sportsline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sportsline_proto_rawDesc), len(file_sportsline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sportsline_proto_goTypes,
		DependencyIndexes: file_sportsline_proto_depIdxs,
		MessageInfos:      file_sportsline_proto_msgTypes,
	}.Build()
	File_sportsline_proto = out.File
	file_sportsline_proto_goTypes = nil
	file_sportsline_proto_depIdxs = nil
}
